### ISSUE TITLE
npm start fails with TypeError

### ISSUE THREAD

**Issue by obfuscurity** [cassidoo/shopify-next-netlify#2]
I'm trying to get this running on my local PC (WSL2 in Windows 10) but running into a problem with `npm start`.

```
$ npm start

> shopify-next-netlify@0.5.0 start /home/jdixon/Projects/shopify-next-netlify
> netlify dev

◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Loaded function add-to-cart.
◈ Loaded function get-cart.
◈ Loaded function get-product-list.
◈ Loaded function get-product.
◈ Loaded function remove-from-cart.
◈ Functions server is listening on 34585
◈ Starting Netlify Dev with #custom

> shopify-next-netlify@0.5.0 dev /home/jdixon/Projects/shopify-next-netlify
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Request from ::ffff:127.0.0.1: GET /.netlify/functions/get-product-list
--------------------------------
Retrieving product list...
--------------------------------
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/jdixon/Projects/shopify-next-netlify/node_modules/node-fetch/lib/index.js:1305:9)
    at /home/jdixon/Projects/shopify-next-netlify/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/home/jdixon/Projects/shopify-next-netlify/node_modules/node-fetch/lib/index.js:1407:9)
    at exports.postToShopify (/home/jdixon/Projects/shopify-next-netlify/functions/utils/postToShopify.js:5:26)
    at Object.exports.handler (/home/jdixon/Projects/shopify-next-netlify/functions/get-product-list.js:25:35)
    at Object._executeSync (/home/jdixon/Projects/shopify-next-netlify/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:286:47)
    at /home/jdixon/Projects/shopify-next-netlify/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:95:26
    at new Promise (<anonymous>)
    at Object.execute (/home/jdixon/Projects/shopify-next-netlify/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:87:16)
Response with status 200 in 11 ms.
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
error - { FetchError: invalid json response body at http://localhost:8888/.netlify/functions/get-product-list reason: Unexpected end of JSON input
    at /home/jdixon/Projects/shopify-next-netlify/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at http://localhost:8888/.netlify/functions/get-product-list reason: Unexpected end of JSON input',
  type: 'invalid-json',
  page: '/' }

```

```
$ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npx: installed 1 in 0.832s

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 20.65 GB / 24.99 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    netlify-cli: ^6.9.9 => 6.9.9
```

**Comment by miahthegreat** [comment]
Having the same issue as well.

**Comment by cassidoo** [comment]
Hmm two questions first while I debug:
1) Do you have the Netlify CLI installed?
2) Do you have your environment variables set up for your own Shopify shop?

**Comment by obfuscurity** [comment]
> 1. Do you have the Netlify CLI installed?

Yes, although I've had to install it locally with `npm install netlify-cli --save-dev`.

> 2. Do you have your environment variables set up for your own Shopify shop?

No, I didn't see anything about this in the README.

**Comment by cassidoo** [comment]
Got it! I didn't clarify what to do after you set up your own shop. Just added instructions and a link to the tutorial blog post:

https://github.com/cassidoo/shopify-next-netlify/commit/294d6f0a31cf34277896641e7d0a5d0bf7254cbd

**Comment by obfuscurity** [comment]
I'll give it a try and report back, thanks.

**Comment by miahthegreat** [comment]
> Got it! I didn't clarify what to do after you set up your own shop. Just added instructions and a link to the tutorial blog post:
> 
> [294d6f0](https://github.com/cassidoo/shopify-next-netlify/commit/294d6f0a31cf34277896641e7d0a5d0bf7254cbd)

I had these environment variables added and the same error still occurs.
Netlify CLI is installed globally as well.

**Comment by miahthegreat** [comment]
I was able to get the absolute URL issue corrected. It was my own doing, I put the shopify URL in the Netlify URL spot.

Now I am just getting a FetchError:

> error - FetchError: invalid json response body at http://localhost:8888/functions/get-product-list reason: Unexpected token < in JSON at position 0
    at \projects\the-kitchen-dink\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStaticProps (\projects\the-kitchen-dink\.next\server\pages\index.js:2518:18)
    at async Object.renderToHTML (\projects\the-kitchen-dink\node_modules\next\dist\server\render.js:329:24)        
    at async doRender (\projects\the-kitchen-dink\node_modules\next\dist\server\next-server.js:1144:38)
    at async \projects\the-kitchen-dink\node_modules\next\dist\server\next-server.js:1236:28
    at async \projects\the-kitchen-dink\node_modules\next\dist\server\response-cache.js:64:36 {
  type: 'invalid-json',
  page: '/'
}
